#
#
# Build the web app for development purposes.
#
#
FROM debian:bookworm AS build-stage
LABEL Maintainer: Tim Molteno "tim@elec.ac.nz"
ARG tart_name

ARG DEBIAN_FRONTEND=noninteractive

# debian setup
RUN apt-get update -y && apt-get install -y \
    curl \
    npm

RUN rm -rf /var/lib/apt/lists/*

RUN mkdir /code
WORKDIR /code

ENV PATH /code/node_modules/.bin:$PATH

COPY ./web-app/package*.json /code/
COPY ./web-app/api_imaging /code/api_imaging

ENV NODE_OPTIONS=--openssl-legacy-provider 
ENV npm_config_jobs=2

RUN npm install

#RUN npm run ng -- build --prod --source-map --base-href=/${tart_name}/ 

COPY . /code

CMD ng serve --host 0.0.0.0
