### This set of services is for the TART telescope in local (non cloud) mode
# You can connect directly yto the TART on port 80
#   Author: Tim Molteno (c) 2026.

x-logging: &default-logging
    driver: "json-file"
    options:
        max-file: "5"
        max-size: "10m"

services:

    # UI listening on port 80. http://localhost:80
    ui:
        image:  ghcr.io/tart-telescope/web_app/viewer-root:main
        depends_on:
            - telescope-api
        volumes:
            - data-volume:/telescope_data
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        restart: always
        ports:
            - 80:80
        logging: *default-logging

    # Proxy for API listening on port 5000. http://localhost:5000/docs
    #
    telescope-api:
        image: ghcr.io/tart-telescope/sbc_code:latest
        volumes:
            -   ~/tart_web_api_store:/database/ # dir where the sqlite database is stored
            -   ~/telescope_config:/config_data # dir where telescope_config.json and calibratied_antenna_positions.json are expected
            -   data-volume:/telescope_data # shared between containers. serving vis and raw hdf files as static files through nginx
        # Comment the following two lines to disable access to the TART hardware (this allows testing of software on a desktop)
        devices:
           - /dev/spidev0.0
        environment:
            # Change the following env vars or create a .env. You will use this to login to your telescope from the Web UI or CLI.
            - LOGIN_PW=${LOGIN_PW}
            - SECRET_KEY=${SECRET_KEY}
            # Optional environment variables for configuring the telescope
            # - CONFIG_DIR=/config
            # - DATA_ROOT=/telescope_data
            # - LOGLEVEL=DEBUG
        ports:
            - 5000:5000
        restart: always
        logging: *default-logging


volumes:
    # Mounted on each container as /telescope_data, used for raw data and vis data. This is a hardcoded path in each container.
    data-volume:
