# DO NOT EDIT! This file is auto-generated from JSON schemas.
# To make changes, edit the schema files and regenerate.

# generated by datamodel-codegen:
#   filename:  acquisition.json
#   timestamp: 2025-07-12T03:44:59+00:00
#   version:   0.31.2

from __future__ import annotations
from typing import Annotated, Any
from pydantic import BaseModel, ConfigDict, Field, RootModel
from enum import Enum


class Model(RootModel[Any]):
    root: Any


class Save(Enum):
    """
    Save flag: 0=disabled, 1=enabled
    """

    integer_0 = 0
    integer_1 = 1


class SaveFlagResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    save: Save
    """
    Save flag: 0=disabled, 1=enabled
    """


class SampleExponentResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    n_samples_exp: Annotated[int, Field(alias="N_samples_exp", ge=16, le=24)]
    """
    Exponent for number of samples (2^exp)
    """
