# DO NOT EDIT! This file is auto-generated from JSON schemas.
# To make changes, edit the schema files and regenerate.

# generated by datamodel-codegen:
#   filename:  calibration.json
#   timestamp: 2025-07-13T01:08:46+00:00
#   version:   0.31.2

from __future__ import annotations
from typing import Annotated, Any
from pydantic import BaseModel, ConfigDict, Field, RootModel


class Model(RootModel[Any]):
    root: Any


class SetGainRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    gain: list[float]
    """
    List of channel gains
    """
    phase_offset: list[float]
    """
    List of channel phase offsets in radians
    """


class AntennaPosition(RootModel[list[float]]):
    root: Annotated[list[float], Field(max_length=3, min_length=3)]


class SetAntennaPositionsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    antenna_positions: list[AntennaPosition]
    """
    Array of antenna positions in East-North-Up coordinate system [[e,n,u],[e,n,u],..]
    """


class GetGainResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    gain: list[float]
    """
    List of channel gains
    """
    phase_offset: list[float]
    """
    List of channel phase offsets in radians
    """


class EmptyResponse(BaseModel):
    pass
    model_config = ConfigDict(
        extra="forbid",
    )
