# DO NOT EDIT! This file is auto-generated from JSON schemas.
# To make changes, edit the schema files and regenerate.

# generated by datamodel-codegen:
#   filename:  data.json
#   timestamp: 2026-03-18T06:17:47+00:00
#   version:   0.55.0

from __future__ import annotations
from typing import Any
from pydantic import BaseModel, ConfigDict, RootModel


class Model(RootModel[Any]):
    root: Any


class FileHandle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    filename: str
    """
    Filename
    """
    checksum: str
    """
    SHA256 checksum
    """
    timestamp: str
    """
    File timestamp
    """


class RawDataResponse(RootModel[list[FileHandle]]):
    root: list[FileHandle]


class VisDataResponse(RootModel[list[FileHandle]]):
    root: list[FileHandle]
