
services:
    # The headscale config file is in config/config.yaml
    headscale:
        image: headscale/headscale:v0.28.0
        container_name: headscale
        volumes:
            - ./config:/etc/headscale/
            - ./hs_data/lib:/var/lib/headscale
            - ./hs_data/run:/var/run/headscale
        entrypoint: headscale serve
        ports:
            # - "8080:8080"
            - "9090:9090"
        healthcheck:
            test: ["CMD", "headscale", "health"]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 40s
            start_interval: 5s
        restart: unless-stopped

    # Caddy proxies both the headscale via cloud.elec.ac.nz, as well as the api.elec.ac.nz
    caddy:
        image: caddy:latest
        container_name: caddy
        restart: unless-stopped
        security_opt:
            - label:disable
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
            
        extra_hosts:
            - "host.docker.internal:172.17.0.1"

        volumes:
            - caddy_data:/data
            - caddy_config:/config
            - ./caddy_etc:/etc/caddy
            - /etc/localtime:/etc/localtime:ro

    headscale-ui:
        image: ghcr.io/gurucomputing/headscale-ui:latest
        restart: unless-stopped
        container_name: headscale-ui
    #     # ports:
    #     #     - 9443:443

    ts-nginx:
        # ts-nginx & nginx required to expose
        # headscale grpc port to the headscale network
        image: tailscale/tailscale:v1.84.3
        restart: unless-stopped
        hostname: headscale-grpc
        ports:
            - 50443:50443
        environment:
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_EXTRA_ARGS=--login-server https://cloud.elec.ac.nz
            - TS_NO_LOGS_NO_SUPPORT=true
            - TS_ACCEPT_DNS=true
            - TS_USERSPACE=false
        devices:
            - /dev/net/tun:/dev/net/tun
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        volumes:
            - ts-grpc-data:/var/lib/tailscale
    nginx:
        image: nginx:latest
        restart: unless-stopped
        volumes:
            - ./grpc-nginx.conf:/etc/nginx/nginx.conf
        network_mode: "service:ts-nginx"


volumes:
  caddy_data:
    external: true
  caddy_config:
  ts-grpc-data:
