# DO NOT EDIT! This file is auto-generated from JSON schemas.
# To make changes, edit the schema files and regenerate.

# generated by datamodel-codegen:
#   filename:  auth.json
#   timestamp: 2025-07-13T01:08:46+00:00
#   version:   0.31.2

from __future__ import annotations
from typing import Any
from pydantic import BaseModel, ConfigDict, RootModel


class Model(RootModel[Any]):
    root: Any


class AuthRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    username: str
    """
    Username for authentication
    """
    password: str
    """
    Password for authentication
    """


class AuthResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    access_token: str
    """
    JWT access token
    """
    refresh_token: str
    """
    JWT refresh token
    """


class RefreshResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    access_token: str
    """
    New JWT access token
    """


class AuthErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    msg: str
    """
    Error message
    """
