# DO NOT EDIT! This file is auto-generated from JSON schemas.
# To make changes, edit the schema files and regenerate.

# generated by datamodel-codegen:
#   filename:  channel.json
#   timestamp: 2025-07-13T01:08:48+00:00
#   version:   0.31.2

from __future__ import annotations
from typing import Annotated, Any
from pydantic import BaseModel, ConfigDict, Field, RootModel
from enum import Enum
from datetime import datetime


class Model(RootModel[Any]):
    root: Any


class BinaryFlag(Enum):
    integer_0 = 0
    integer_1 = 1


class EmptyResponse(BaseModel):
    pass
    model_config = ConfigDict(
        extra="forbid",
    )


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    msg: str


class Message(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    description: str
    error: str
    status_code: int


class JWTErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    message: Message


class JWTAuthHeader(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    authorization: Annotated[
        str,
        Field(
            alias="Authorization",
            pattern="^JWT [A-Za-z0-9-_]+\\.[A-Za-z0-9-_]+\\.[A-Za-z0-9-_]+$",
        ),
    ]


class ChannelIndex(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=23)]


class TelescopeMode(Enum):
    off = "off"
    diag = "diag"
    raw = "raw"
    vis = "vis"
    vis_save = "vis_save"
    cal = "cal"
    rt_syn_img = "rt_syn_img"


class LoopMode(Enum):
    loop = "loop"
    single = "single"
    loop_n = "loop_n"


class LoopCount(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=100)]


class SampleExponent(RootModel[int]):
    root: Annotated[int, Field(ge=16, le=24)]


class FPGABinaryFlag(Enum):
    integer_0 = 0
    integer_1 = 1


class FPGAStateFlag(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=7)]


class UTCTimestamp(RootModel[datetime]):
    root: datetime


class Hostname(RootModel[str]):
    root: str


class Frequency(RootModel[float]):
    root: Annotated[float, Field(ge=0.0)]


class Coordinate(RootModel[float]):
    root: float


class Altitude(RootModel[float]):
    root: Annotated[float, Field(ge=0.0, le=8848.0)]
    """
    Altitude in meters above sea level (0 to 8848m - Mt. Everest height)
    """


class AntennaPosition(RootModel[list[float]]):
    root: Annotated[list[float], Field(max_length=3, min_length=3)]


class AntennaPositions(RootModel[list[AntennaPosition]]):
    root: list[AntennaPosition]


class Filename(RootModel[str]):
    root: str


class Checksum(RootModel[str]):
    root: str


class RadioMean(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mean: float
    """
    Radio mean value
    """
    ok: BinaryFlag
    """
    Radio mean OK flag
    """
    threshold: Annotated[float, Field(ge=0.0)]
    """
    Radio mean threshold
    """


class ChannelStatus(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    channel_id: ChannelIndex
    """
    Channel ID
    """
    enabled: BinaryFlag
    """
    Channel enabled status
    """


class ChannelStatusResponse(RootModel[list[ChannelStatus]]):
    root: list[ChannelStatus]


class ChannelToggleResponse(RootModel[dict[str, BinaryFlag]]):
    root: dict[str, BinaryFlag]


class PhaseInfo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    n_samples: Annotated[int, Field(alias="N_samples", ge=0)]
    """
    Number of samples
    """
    measured: float
    """
    Measured phase value
    """
    ok: BinaryFlag
    """
    Phase measurement OK flag
    """
    stability: Annotated[float, Field(ge=0.0, le=1.0)]
    """
    Phase stability value
    """
    threshold: Annotated[float, Field(ge=0.0, le=1.0)]
    """
    Phase threshold value
    """


class ChannelInfo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: ChannelIndex
    """
    Channel ID
    """
    enabled: BinaryFlag
    """
    Channel enabled flag
    """
    phase: PhaseInfo
    radio_mean: RadioMean
    freq: list[float]
    """
    Frequency array
    """
    power: list[float]
    """
    Power array
    """


class ChannelInfoResponse(RootModel[list[ChannelInfo]]):
    root: list[ChannelInfo]


class SingleChannelResponse(RootModel[ChannelInfo]):
    root: ChannelInfo
