#
#   nginx sidecar config — routes requests within the tailnet to telescope hosts
#

worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format proxy_log '[$time_local] $remote_addr - $remote_user "$host$request_uri" '
                         '$status $body_bytes_sent "$http_referer" '
                         '"$http_x_forwarded_for"'
                         ' Proxy: "$proxy_host" "$upstream_addr"';

    access_log /var/log/nginx/access.log proxy_log;

    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        server_name _;

        gzip on;
        gzip_types text/plain application/json;

        set $tailnet telescopes.elec.ac.nz;

        root /var/www/html;
        index index.html;

        location ~ ^/tart/(?<tartname>[^/]+)/(?<tarturl>.*)$ {
            rewrite_log on;

            resolver 100.100.100.100;
            set $upstream $tartname.$tailnet:80;

            proxy_pass http://$upstream/$tarturl;
        }

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
